services:
  postgres:
    restart: always
    image: postgres:latest
    container_name: postgres
    env_file:
      - path: .env
        required: false
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
    volumes:
      - .:/api
    env_file:
      - path: .env
        required: false
    command: >
      sh -c "while ! pg_isready -h 'postgres' -U ${POSTGRES_USER}; do
          echo 'Waiting for postgres to be ready...'
          sleep 1
      done;
      echo 'Postgres is ready';
      python manage.py migrate &&
      gunicorn hesapvitrini.asgi:application --bind 0.0.0.0:8000 -w 4 -k hesapvitrini.workers.UvicornWorker"
      
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always